services:
  redis:
    image: valkey/valkey:8.1.2
  rabbitmq:
    image: rabbitmq:4.1.2
  client:
    build: client
    env_file:
      - .env
    command: deploy/startup.dev.sh
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./client/finiteViz:/app
  web_server:
    hostname: web_server
    build: web_server
    ports:
      - 127.0.0.1:8000:3000
    env_file:
      - .env
    volumes:
      - ./web_server:/app/web_server
    depends_on:
      - redis
      - rabbitmq

  # compute_worker:
  #   build: compute_worker
  # env_file:
  # - .env
  #   ports:
  #     - 3000:3000
